// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: event.sql

package model

import (
	"context"
)

const insertEvent = `-- name: InsertEvent :one
INSERT INTO event ( id_line_event, id_chain_event)
VALUES ( $1, $2) RETURNING id_event, id_line_event, id_chain_event, created_at
`

type InsertEventParams struct {
	IDLineEvent  int32 `json:"id_line_event"`
	IDChainEvent int32 `json:"id_chain_event"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent, arg.IDLineEvent, arg.IDChainEvent)
	var i Event
	err := row.Scan(
		&i.IDEvent,
		&i.IDLineEvent,
		&i.IDChainEvent,
		&i.CreatedAt,
	)
	return i, err
}
